### ISSUE TITLE
SSL Verification

### ISSUE THREAD

**Issue by mdaxido** [stark0de/nginxpwner#3]
Hi, 

For those testing servers with incorrect SSL certificates, the script is not working.

The fix is to modify every call to requests.get by adding the "verify=False" option.
`requests.get(..., verify=False)`

I suggest also adding : 
`requests.packages.urllib3.disable_warnings() `
after the : `import requests`
In order to avoid warnings each time the requests.get is called ...

Regards, MD

**Comment by stark0de** [comment]
Thanks for the info, just resolved this
