### ISSUE TITLE
Request of newest nginx version seems to be broken

### ISSUE THREAD

**Issue by 1989gironimo** [stark0de/nginxpwner#9]
Getting this, while executing nginxpwner:
`Traceback (most recent call last):
  File "/opt/nginxpwner/nginxpwner.py", line 47, in <module>
    last_version =(soup.findAll('a', attrs={'href': re.compile("^/nginx/nginx/releases/tag")})[0].get('href')).split("-")[1]
IndexError: list index out of range`

Fixed it temporarily with hardcoding the version number, but it seems that the request to [/nginx/nginx/releases/tag](url) isn't successful somehow, any insights?

**Comment by scarnato** [comment]
Having same problem

**Comment by lnaphade** [comment]
same problem,broken

**Comment by bakwc** [comment]
+

**Comment by stark0de** [comment]
Hey, sorry for the delay guys, didn't notice this, already merged a commit from @cornerpirate which solves this issue
